<a href="https://colab.research.google.com/github/poolaNaveen/Data-Engineering/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
import numpy as np
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]])
print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [4]:
#What is the **total revenue** generated across all stores?
total_revenue = np.sum(retail_data[:, 1])
print(total_revenue)

335000


In [5]:
#Which store recorded the **highest sales**?
highest_sales_store = np.argmax(retail_data[:, 1]) + 1
print(highest_sales_store)

9


In [6]:
#Which store recorded the **lowest sales**?
lowest_sales_store = np.argmin(retail_data[:, 1]) + 1
print(lowest_sales_store)


1


In [7]:
#What is the **average daily sales** per store?
average_daily_sales = np.mean(retail_data[:, 1])
print(average_daily_sales)

33500.0


In [8]:
#How many stores achieved sales **above ₹35,000**?
stores_above_35k = np.sum(retail_data[:, 1] > 35000)
print(stores_above_35k)

3


In [ ]:
#6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

In [9]:
#7. What is the **average number of customers** per store?
retail_data[:,2].mean()

np.float64(425.0)

In [10]:
#8. How many stores have **more than 450 customers**?
a=retail_data[:,2]
s=a[a>450]
s

array([500, 480, 550])

In [11]:
#9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1


np.int64(1)

In [12]:
#10. Is there any store where **high sales do not correspond to high customers**?
s = retail_data[:,1].mean()
c = retail_data[:,2].mean()
m = retail_data[(retail_data[:,1] > s) & (retail_data[:,2] < c)]
m

array([[    5, 35000,   420,  1400,    12]])